### ISSUE TITLE
build script --> no mounted routes

### ISSUE THREAD

**Issue by pmc-sstaehle** [scopsy/node-typescript-starter#1]
Hi there,
first of all I wanted to say thank you, your project is a really good starter for API-based projects. I have a question respectively wanted to report an possible error.
When I want to build my project for the production, I have to problem, that there are no mounted routes. When I'm runniung the start-script, everthing is fine and works, but not after the build and start:prod script. As I said there are no routes listed in the overview at the start o the server. My output is something like this:
`[2018-01-23T08:27:07.783] [INFO ] [TSED] - Build services
body-parser deprecated bodyParser: use individual json/urlencoded middlewares dist\server.js:38:22
body-parser deprecated undefined extended: provide extended option node_modules\body-parser\index.js:105:29
[2018-01-23T08:27:07.807] [INFO ] [TSED] - Build controllers

[2018-01-23T08:27:07.810] [INFO ] [TSED] - Routes mounted :

[2018-01-23T08:27:07.812] [INFO ] [TSED] - 
┌────────┬──────────┬──────────────┐
│ Method │ Endpoint │ Class method │
└────────┴──────────┴──────────────┘

[2018-01-23T08:27:07.856] [INFO ] [TSED] - HTTP Server listen on http://0.0.0.0:3000
Server started...

[2018-01-23T08:27:07.858] [INFO ] [TSED] - Started in 194 ms

[2018-01-23T08:27:07.859] [INFO ] [TSED] - Server started...
`
Can you please advice me what to do?

Another point is that I had to change the start:prod script. It should be:
`"start:prod": "node dist/app.js",`
insted of 
`"start:prod": "node dist/main.js",`

Thank you!

**Comment by scopsy** [comment]
@pmc-sstaehle Thanks using the starter!

I've uploaded a fix commit that fixes the prod:start issue.

The main thing to notice is the ending of the mounting points:
```
    mount: {
        '/v1': `${rootDir}/controllers/**/**.controller.{ts,js}`
    },
    componentsScan: [
        `${rootDir}/services/**/**.service.{ts,js}`,
        `${rootDir}/middlewares/**/**.{ts,js}`,
        `${rootDir}/dal/**/**.{ts,js}`
    ],
```

I suggest you fork the latest version of the starter. I added example unit tests and other fixes.

**Comment by pmc-sstaehle** [comment]
Thanks! That solved the problem.

**Comment by scopsy** [comment]
@pmc-sstaehle Great, I opened an issue for ts-express-decorators library to add a fallback if `.ts` is not available so you won't be needed to use this `*.{ts,js}` syntax.
