### ISSUE TITLE
QST - Logged -In User

### ISSUE THREAD

**Issue by pmc-sstaehle** [scopsy/node-typescript-starter#2]
Hi @scopsy ,
is it possible to get the actual loggedIn user by the token within a service/controller? How can I do this?

Thanks and best regards!

**Comment by ComBarnea** [comment]
hi @pmc-sstaehle 
Just added another route to user controller, you can access user token data with req.user, look at new route as a working example.

**Comment by pmc-sstaehle** [comment]
Very nice! Thank you very much!
