### ISSUE TITLE
Geeting User not found all the time on login /v1/auth/login.

### ISSUE THREAD

**Issue by goors** [scopsy/node-typescript-starter#6]
I am getting all the time user not found:

```
{
    "message": "User not found.",
    "code": 2001,
    "status": 404
}
```

When sending JSON with:

```
{
"email":"me@gmail.com",
"password":"password"
}
```

In local strategy:

```
const user = await this.userRepository.findOne({ email }, this.USER_TOKEN_FIELDS + ' password');
if (!user) throw new ApiError(API_ERRORS.USER_NOT_FOUND);
```

Of course this is not correct since that user exists in database.

**Comment by ShareinSK** [comment]
Have you created any new controllers other than the given auth and user controller?

**Comment by goors** [comment]
I gave up on this since i spent to much time getting same errro all the time. Closing
